### ISSUE TITLE
Crashing on Androod 14

### ISSUE THREAD

**Issue by Rigerhit047** [ThisIsSidam/rem-reminds-you#1]
First for all, this app is exactly what I was looking for, I'm glad it exists

However, as you said, it really crashes on Android 14.

After installing the app or removing the app data, the app crashes one time, then it launches normally asking for notification permission, and when when you are in the middle of creating a reminder it crashes, and any future attempt to open it results in a crash. 

Here's a crash log when I attempt to open the app:

```
FATAL EXCEPTION: main
Process: rem.reminds.you, PID: 1597
java.lang.RuntimeException: Unable to create service id.flutter.flutter_background_service.BackgroundService: android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{feb6e7d 1597:rem.reminds.you/u0a569} targetSDK=34
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4697)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2290)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8284)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:885)
Caused by: android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{feb6e7d 1597:rem.reminds.you/u0a569} targetSDK=34
	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:53)
	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:49)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4870)
	at android.os.Parcel.readParcelable(Parcel.java:4852)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3052)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6825)
	at android.app.Service.startForeground(Service.java:862)
	at androidx.core.app.k1.a(Unknown Source:0)
	at androidx.core.app.l1$b.a(Unknown Source:14)
	at androidx.core.app.l1.a(Unknown Source:6)
	at id.flutter.flutter_background_service.BackgroundService.updateNotificationInfo(Unknown Source:85)
	at id.flutter.flutter_background_service.BackgroundService.onCreate(Unknown Source:70)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4684)
	... 9 more
```

If you do need any other logs, I will be happy to provide.

**Comment by ThisIsSidam** [comment]
@Rigerhit047  This is exactly what I needed. I do get some solutions with this and I will release the next beta with the fix by tonight. I will tell you if I needed anything else. Thanks.

**Comment by ThisIsSidam** [comment]
@Rigerhit047 I released the version with fix. Please check if it still crashes.

**Comment by Rigerhit047** [comment]
@ThisIsSidam Just installed it, tested doing anything I could, it doesn't seem to crash anymore, it seems it's fixed!
